// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs7kbS8LiKpk0GwifsE-cH7q4FDQrVyg0',
    appId: '1:892548569518:web:8a608551afbbc38ec3503f',
    messagingSenderId: '892548569518',
    projectId: 'chat-app-7761f',
    authDomain: 'chat-app-7761f.firebaseapp.com',
    storageBucket: 'chat-app-7761f.firebasestorage.app',
    measurementId: 'G-1HLK952WZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_N27BfUbOKBTlhYuPm6s4fG8vAZnK61c',
    appId: '1:892548569518:android:bcfd42939ddf3d10c3503f',
    messagingSenderId: '892548569518',
    projectId: 'chat-app-7761f',
    storageBucket: 'chat-app-7761f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2j6XE_2fHzatIYc04lH-0WslI_Rnbj8A',
    appId: '1:892548569518:ios:0e73c0bd7ebabc69c3503f',
    messagingSenderId: '892548569518',
    projectId: 'chat-app-7761f',
    storageBucket: 'chat-app-7761f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2j6XE_2fHzatIYc04lH-0WslI_Rnbj8A',
    appId: '1:892548569518:ios:0e73c0bd7ebabc69c3503f',
    messagingSenderId: '892548569518',
    projectId: 'chat-app-7761f',
    storageBucket: 'chat-app-7761f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs7kbS8LiKpk0GwifsE-cH7q4FDQrVyg0',
    appId: '1:892548569518:web:00332106c9505615c3503f',
    messagingSenderId: '892548569518',
    projectId: 'chat-app-7761f',
    authDomain: 'chat-app-7761f.firebaseapp.com',
    storageBucket: 'chat-app-7761f.firebasestorage.app',
    measurementId: 'G-6SFMVYX6JM',
  );
}
